//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba3EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetFullInfo
    {
        public int ID_Game { get; set; }
        public string Game_Name { get; set; }
        public int ID_Platform { get; set; }
        public string Platform_Name { get; set; }
        public Nullable<int> Developers_ID { get; set; }
        public string Studio_Name { get; set; }
        public Nullable<int> Studio_Age { get; set; }
        public string Studio_Owner { get; set; }
    }
}
